import './globals.css'
import { Inter } from 'next/font/google'
import { AuthProvider } from "@propelauth/nextjs/client";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<AuthProvider authUrl={process.env.NEXT_PUBLIC_AUTH_URL}>
				<body className={inter.className}>{children}</body>
			</AuthProvider>
		</html>
	)
}
